#!/bin/bash
set -e
set -o pipefail

if [[ ! -z "$TOKEN" ]]; then
	TF_ENV_TOKEN=$TOKEN
fi

if [[ -z "$TF_ENV_TOKEN" ]]; then
	echo "Set the TF_ENV_TOKEN env variable."
	exit 1
fi

/bin/cat > .terraformrc << EOM
credentials "app.terraform.io" {
  token = "$TF_ENV_TOKEN"
}
EOM
